# Generated by Django 3.2.6 on 2022-06-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='image',
            new_name='patientImage',
        ),
    ]
