# Generated by Django 3.2.6 on 2022-06-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0003_alter_patient_patientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
