# Generated by Django 3.2.6 on 2022-06-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0004_alter_patient_patientimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorImage', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('Education', models.CharField(max_length=400)),

            ],
        ),
    ]
