# Generated by Django 3.2.6 on 2022-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0005_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Covid Essentials', 'Covid Essentials'), ('Ayurvedic', 'Ayurvedic'), ('Homeopathy', 'Homeopathy'), ('Fitness', 'Fitness'), ('Surgical', 'Surgical'), ('Sexual Wellness', 'Sexual Wellness')], max_length=50)),
            ],
        ),
    ]
