# Generated by Django 3.2.6 on 2022-07-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0012_alter_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletters',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patients', 'verbose_name_plural': 'Patients'},
        ),
    ]
