# Generated by Django 3.2.6 on 2022-07-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0013_auto_20220714_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ('name',), 'verbose_name': 'Pharmacy', 'verbose_name_plural': 'Pharmachies'},
        ),
    ]
