# Generated by Django 3.2.6 on 2022-07-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0014_alter_pharmacy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Doctors', 'verbose_name_plural': 'Doctors'},
        ),
    ]
