# Generated by Django 3.2.6 on 2022-07-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0015_auto_20220714_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'DoctorCategories',
                'verbose_name_plural': 'DoctorCategories',
            },
        ),
    ]
