# Generated by Django 3.2.6 on 2022-07-16 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0019_alter_doctors_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='categories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicApp.doctorcategories'),
        ),
    ]
