# Generated by Django 3.2.6 on 2022-07-16 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0021_alter_doctorcategories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcategories',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='categories',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicApp.doctorcategories'),
        ),
    ]
